-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
